### ISSUE TITLE
[BUG] sbt run hangs

### ISSUE THREAD

**Issue by marmoure** [eXist-db/exist-xqts-runner#36] opened 2022-09-16 11:32 UTC
seems like following how to run from compiled source section in the README makes it hang
eg: 
`sbt "run --xqts-version HEAD --test-set method-json"`
will produce
```shell
$ sbt "run --xqts-version HEAD --test-set method-json"
[info] welcome to sbt 1.6.2 (BellSoft Java 1.8.0_345)
[info] loading settings for project exist-xqts-runner-build from license.sbt,plugins.sbt ...
[info] loading project definition from /home/ubuntu/testdir/exist-xqts-runner/project
[info] loading settings for project exist-xqts-runner from build.sbt ...
[info] set current project to exist-xqts-runner (in build file:/home/ubuntu/testdir/exist-xqts-runner/)
[warn] Credentials file /home/ubuntu/.ivy2/.credentials does not exist
[warn] Credentials file /home/ubuntu/.ivy2/.credentials does not exist
[warn] Credentials file /home/ubuntu/.ivy2/.credentials does not exist
[info] running org.exist.xqts.runner.XQTSRunner --xqts-version HEAD --test-set method-json
16 Sep 2022 08:58:37,541 [sbt-bg-threads-1] INFO  (slf4j.scala [info]:159) - eXist-db XQTS Runner starting for: XQTS_HEAD
16 Sep 2022 08:58:38,186 [sbt-bg-threads-1] INFO  (slf4j.scala [info]:159) - Could not find XQTS at: work/qt3tests-master, checking for downloaded copy...
16 Sep 2022 08:58:38,187 [sbt-bg-threads-1] INFO  (slf4j.scala [info]:159) - No downloaded copy found, downloading XSTS from: https://github.com/w3c/qt3tests/archive/master.zip to work...
16 Sep 2022 08:58:45,133 [sbt-bg-threads-1] INFO  (slf4j.scala [info]:159) - Expanding XQTS from: work/master.zip to: work
16 Sep 2022 08:58:47,050 [sbt-bg-threads-1] INFO  (slf4j.scala [info]:159) - Starting an embedded instance of eXist-db...
16 Sep 2022 08:58:47,072 [sbt-bg-threads-1] WARN  (ConfigurationHelper.java [getExistHome]:133) - conf.xml file was found on the classpath, but inside a Jar file! Derived EXIST_HOME from Jar's parent folder: /home/ubuntu/testdir/exist-xqts-runner/target/bg-jobs/sbt_631f6fb3/job-1/target/17511934/ed85cc9a
16 Sep 2022 08:58:47,128 [sbt-bg-threads-1] WARN  (ConfigurationHelper.java [getExistHome]:133) - conf.xml file was found on the classpath, but inside a Jar file! Derived EXIST_HOME from Jar's parent folder: /home/ubuntu/testdir/exist-xqts-runner/target/bg-jobs/sbt_631f6fb3/job-1/target/17511934/ed85cc9a
16 Sep 2022 08:58:47,199 [sbt-bg-threads-1] WARN  (ConfigurationHelper.java [getExistHome]:133) - conf.xml file was found on the classpath, but inside a Jar file! Derived EXIST_HOME from Jar's parent folder: /home/ubuntu/testdir/exist-xqts-runner/target/bg-jobs/sbt_631f6fb3/job-1/target/17511934/ed85cc9a
16 Sep 2022 08:58:47,461 [sbt-bg-threads-1] WARN  (ConfigurationHelper.java [getExistHome]:133) - conf.xml file was found on the classpath, but inside a Jar file! Derived EXIST_HOME from Jar's parent folder: /home/ubuntu/testdir/exist-xqts-runner/target/bg-jobs/sbt_631f6fb3/job-1/target/17511934/ed85cc9a
16 Sep 2022 08:58:47,462 [sbt-bg-threads-1] WARN  (QuartzSchedulerImpl.java [getQuartzProperties]:149) - Could not load Quartz Scheduler properties, will use defaults.
16 Sep 2022 08:58:48,258 [sbt-bg-threads-1] INFO  (slf4j.scala [info]:159) - eXist-db 6.0.1 (51506fc) OK.
16 Sep 2022 08:58:48,298 [XQTSRunnerSystem-akka.actor.default-dispatcher-9] INFO  (slf4j.scala [info]:159) - Running XQTS: XQTS_HEAD
[success] Total time: 14 s, completed Sep 16, 2022 8:58:48 AM
16 Sep 2022 08:58:48,351 [XQTSRunnerSystem-akka.actor.default-dispatcher-13] INFO  (slf4j.scala [info]:159) - Parsing XQTS Catalog: work/qt3tests-master/catalog.xml...
16 Sep 2022 08:58:48,495 [XQTSRunnerSystem-akka.actor.default-dispatcher-9] INFO  (slf4j.scala [info]:159) - Parsing XQTS TestSet: work/qt3tests-master/ser/method-json.xml...
16 Sep 2022 08:58:48,495 [XQTSRunnerSystem-akka.actor.default-dispatcher-13] INFO  (slf4j.scala [info]:159) - Parsed XQTS Catalog OK.
16 Sep 2022 08:58:48,499 [XQTSRunnerSystem-akka.actor.default-dispatcher-8] INFO  (slf4j.scala [info]:159) - Matched 1 Test Sets in XQTS HEAD...
```
and it will just hangs

**Comment by marmoure** [comment] 2022-09-16 11:33
even trying to terminate the process using `CTRL+C` on the cli doesn't work
you have to `kill -9` it

**Comment by adamretter** [comment] 2022-09-20 08:29
Closing as a duplicate of https://github.com/eXist-db/exist-xqts-runner/issues/22

**Closed by adamretter** 2022-09-20 08:29 UTC
